-- begin CARDEALER_CAR
alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_CAR_MODEL_ID foreign key (CAR_MODEL_ID) references CARDEALER_CAR_MODEL(ID)^
alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_CARD_ID foreign key (CARD_ID) references WF_CARD(ID)^
create index IDX_CARDEALER_CAR_CAR_MODEL on CARDEALER_CAR (CAR_MODEL_ID)^
-- end CARDEALER_CAR
-- begin CARDEALER_CAR_PURCHASE_APPLICATION
alter table CARDEALER_CAR_PURCHASE_APPLICATION add constraint FK_CARDEALER_CAR_PURCHASE_APPLICATION_CAR_ID foreign key (CAR_ID) references CARDEALER_CAR(CARD_ID)^
alter table CARDEALER_CAR_PURCHASE_APPLICATION add constraint FK_CARDEALER_CAR_PURCHASE_APPLICATION_CLIENT_ID foreign key (CLIENT_ID) references DF_CONTRACTOR(CORRESPONDENT_ID)^
alter table CARDEALER_CAR_PURCHASE_APPLICATION add constraint FK_CARDEALER_CAR_PURCHASE_APPLICATION_BANK_ID foreign key (BANK_ID) references DF_BANK(ID)^
alter table CARDEALER_CAR_PURCHASE_APPLICATION add constraint FK_CARDEALER_CAR_PURCHASE_APPLICATION_CARD_ID foreign key (CARD_ID) references DF_DOC(CARD_ID)^
create index IDX_CARDEALER_CAR_PURCHASE_APPLICATION_CLIENT on CARDEALER_CAR_PURCHASE_APPLICATION (CLIENT_ID)^
create index IDX_CARDEALER_CAR_PURCHASE_APPLICATION_CAR on CARDEALER_CAR_PURCHASE_APPLICATION (CAR_ID)^
create index IDX_CARDEALER_CAR_PURCHASE_APPLICATION_BANK on CARDEALER_CAR_PURCHASE_APPLICATION (BANK_ID)^
-- end CARDEALER_CAR_PURCHASE_APPLICATION
